### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Groocery** [ISU-PAAL/DeepDFA#2]
When I run `python -u sastvd/scripts/dbize.py`, there is a 'NoneType' error when executing line 205 of `DDFA/sastvd/helpers/evaluate.py:before_graph = feature_extraction(filepath_before)[0] `.

The error message is:
```
Traceback (most recent call last):
  File "sastvd/scripts/dbize.py", line 26, in <module>
    dep_add_lines = ivde.get_dep_add_lines_bigvul()
  File "/DDFA/sastvd/helpers/evaluate.py", line 282, in get_dep_add_lines_bigvul
    return get_dep_add_lines("bigvul", cache, sample)
  File "/DDFA/sastvd/helpers/evaluate.py", line 205, in get_dep_add_lines
    before_graph = feature_extraction(filepath_before)[0]
TypeError: 'NoneType' object is not subscriptable
```

It appears that when I carefully reviewed the function calls within the `evaluate.py` file, I noticed that the function `get_dep_add_lines_bigvul()` is calling the `get_dep_add_lines("bigvul", cache, sample)` function, but the parameters being passed do not match the expected parameters in the `get_dep_add_lines(filepath_before, filepath_after, added_lines)` function defined in the same file. Despite having the same number of parameters, this mismatch is causing the function to return `None`. I would like to confirm whether there is an issue with parameter passing and understand how to correctly pass the parameters. What should be the correct way to pass the parameters?

**Comment by bstee615** [comment]
Thanks for checking out the project!

If I understand correctly, your error occurs because the result of `feature_extraction(filepath_before)` at line 205 is None. This function retrieves the function's graph representation from a file on disk. It will return None if the file is missing from disk, and it probably returns None because the filename passed does not exist, see the code here: https://github.com/ISU-PAAL/DeepDFA/blob/master/DDFA/sastvd/helpers/evaluate.py#L47-L50

To fix the issue, please ensure that you do the following:
1. Run getgraphs.py properly and check that the graph representation files are present at the path defined as `svd.processed_dir() / row["dataset"] / "before"`. This is the script: [run_getgraphs.sh](https://github.com/ISU-PAAL/DeepDFA/blob/master/DDFA/scripts/run_getgraphs.sh). Even if invoked correctly, the call to `feature_extraction` will fail if these graph representation files are not present.
2. Comment out [the extra function definition on line 258](https://github.com/ISU-PAAL/DeepDFA/blob/070ddb998a2ed4ed3026972820e9cd8512960e6d/DDFA/sastvd/helpers/evaluate.py#L258-L259), so that [the definition on line 239 is used](https://github.com/ISU-PAAL/DeepDFA/blob/070ddb998a2ed4ed3026972820e9cd8512960e6d/DDFA/sastvd/helpers/evaluate.py#L239). It looks like the definition on line 258 incorrectly overwrites the definition of `get_dep_add_lines` and should be removed - I might have added this in testing before releasing the code. My apologies, this code may not all be updated perfectly as I haven't got time to test the whole thing thoroughly yet.
3. If you still get the issue, try setting a breakpoint [inside the feature_extraction function](https://github.com/ISU-PAAL/DeepDFA/blob/070ddb998a2ed4ed3026972820e9cd8512960e6d/DDFA/sastvd/helpers/evaluate.py#L39) and step through the function to see why it's returning None.

I hope this helps to fix the problem. Please let me know. Thanks!

**Comment by Groocery** [comment]
Thanks for your response! 

Based on your advice, the issue has been resolved.

 I commented out line 258 in `DDFA/sastvd/helpers/evaluate.py` and made a modification to line 239 as follows: I changed `get_dep_add_lines_bigvul(dataset, cache, sample)` to `get_dep_add_lines_bigvul(dataset, cache=True, sample=False)`. Additionally, I assigned the appropriate parameter to `dataset` when calling this function.

**Comment by bstee615** [comment]
Glad it worked out. Feel free to submit a PR with this and any other fixes you make!

**Comment by bstee615** [comment]
FYI I've updated this repository with tested and working instructions for running the experiments, and fixed the bugs which were reported as of recent. Hope it helps!

**Comment by mcf20** [comment]
> 感谢您的回复！
> 
> 根据您的建议，问题已得到解决。
> 
> 我注释掉了第 258 行，并对第 239 行进行了修改，如下所示：我更改为 .此外，我在调用此函数时分配了适当的参数。`DDFA/sastvd/helpers/evaluate.py``get_dep_add_lines_bigvul(dataset, cache, sample)``get_dep_add_lines_bigvul(dataset, cache=True, sample=False)``datas您好 您复现出来了么 可以请教一下如何复现该项目么
