### ISSUE TITLE
Questions About Dataset Preparation Scripts

### ISSUE THREAD

**Issue by habaneraa** [ISU-PAAL/DeepDFA#3]
Hi! DeepDFA is a very interesting model and I have managed to reproduce its performance on pre-processed graph data. It seems that models solely based on dataflow features have strong potential for detecting vulnerabilities, comparing to text/semantic based transformers, which are largely unaware of code dependency.

However, I encountered some issues when I tried to run the script that preprocesses bigvul dataset (at `DDFA/sastvd/scripts/prepare.py`). 

https://github.com/ISU-PAAL/DeepDFA/blob/070ddb998a2ed4ed3026972820e9cd8512960e6d/DDFA/sastvd/scripts/prepare.py#L7-L12

Line 10, `get_dep_add_lines()` got an unexpected keyword argument "sample". And I could not find any module named `svdglove` or `svdd2v` in the project. 

Looking forward to your reply. Thanks!

**Comment by bstee615** [comment]
Thanks for your kind message!

sample is likely an outdated argument used for testing on a small sample of the dataset -- please follow the same steps to use this function as this user. https://github.com/ISU-PAAL/DeepDFA/issues/2#issuecomment-1778550966
The prepare.py script only pre-caches data so that later scripts can be run from the cached data, but if you are blocked on some further error with this script, you may want to bypass this script and try setting up the rest of the project.

GLoVE and Doc2Vec are holdovers from the LineVD project, which is the foundation for DeepDFA's code. Feel free to comment out these lines.

Good luck! Please feel free to submit a PR if you make some changes which help to run the code more easily!

**Comment by habaneraa** [comment]
Thank you for the answer! I have realized that the `svdglove` and `svdd2v` have nothing to do with DeepDFA. They should be commented out. 

Closing this issue as completed.

**Comment by bstee615** [comment]
FYI I've updated this repository with tested and working instructions for running the experiments, and fixed the bugs which were reported as of recent. Hope it helps!
